# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=b'')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Session'),
        ),
    ]
